### ISSUE TITLE
Bug: When enabled, Obsidian interprets keystrokes differently

### ISSUE THREAD

**Issue by chrisgrieser** [Stardusten/ob-table-enhancer#40] opened 2023-01-25 16:29 UTC
So I noticed that Obsidian global keystroke behavior changes, not only keystrokes related to this plugin.

For example, the hotkey `alt+shift+t`. On Mac, this normally creates a special character: `˝`. However, with Obsidian, I can bind a command to `alt+shift+t`, so that Obsidian will execute that command rather than inserting a `˝`. 

Now when the table-enhancer is installed, this behavior changes. Now `alt+shift+t` will trigger the command **and** also insert the `˝` character.

Similar things happen with various other hotkey combinations, e.g. `cmd+h` will normally hide a window on Mac, I can rebind it to some command, but as soon as the table enhancer is installed, that command does not work anymore.

**Comment by ggstrader** [comment] 2023-01-26 06:39
I also noticed an issue with "ctrl+enter" which I have set to "Cycle  bullet/checkbox", it now inserts a newline after the bullet forcing me to "backspace" to get back to the bullet.

**Comment by Stardusten** [comment] 2023-01-26 07:11
I did some testing and it showed that this was caused by the monkey patch I was using. But I don't know what the problem is. So I will release a temporary version where the monkey patch was disabled later.

**Comment by Stardusten** [comment] 2023-02-03 03:13
Should be fixed in the latest release.

**Closed as completed** 2023-02-03 03:13 UTC
